@url_dev = http://localhost:5000/v1/api/access/

### Sign up
POST {{url_dev}}user/signup
Content-Type: application/json

{
    "fullname": "saidep112",
    "username": "zaidep112",
    "email": "zaidep112@gmail.com",
    "password": "ngtd@ngA12311n2gA123"
}

### Login
POST {{url_dev}}user/login
Content-Type: application/json

{
    "email": "zaidep112@gmail.com",
    "password": "ngtd@ngA12311n2gA123"
}

### Logout
POST {{url_dev}}user/logout
Content-Type: application/json
x-client-id: 66cd5835679db0d2bbe6ec47
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmQ0MzQ2NGRiN2RjOWFmOWQyYjU3NzciLCJlbWFpbCI6InRua2p5QGdtYWlsLmNvbSIsImlhdCI6MTcyNTE4MzA3NywiZXhwIjoxNzI1MzU1ODc3fQ.nuKwwDC458HcgWPOAyB8cApMpr8DNui5YQOptvhmycslOe9ipFacwobgB2DMKxrYcDUs9x8dqo7NMMM6pBUO6CJ32ggP-9y093T3o3UzU5mVvKGzZZmf94nc4r7beEg_tWfXKvAJJwZY2Rjj4xiZ6YIeK2UEJ88DE9U04lKLVeCPlVsfm8yE1obYzDbdqGJOKDunzj8Qxff2XsmChB2loiqOwPCYuZKWFHmWGh9uOB056wDyKrsfDXYpaHvTpjVPz86aM9NY1jfxypCG2HJGTRuxpNwlhXiHDWFBggSI9o8rlEWBYalb0S08xl329HiyRLRln9DdjWIa1PQpcRQX1iCqflRETFDS2XGD9kSOZ4AbaaK-6QhWH4zkEFpLhamGyebFhyMdJWxdB2OuATEWZifTuytXYC_phyLWKkwGhPflcg6oaltymYj5Xs4YMxKWBabXYA69p0CEQC2djMal0ayaODcu7AbetSu2TRZW1UbfYh7bEcJSuQEzYjeZIw6LxmfNeZNGDzxeSm_BZ2HBKwrlVp1Pxg25KWPW5BpE2vMISZA-JzdHJlZC9A0jRZJnJ43hPw9rI43wXdnQVVLfDFfZ0Cv0DtAVwDUPpKv6XKQZvbnBizw0x7wNkn7AN7M_KUlsNXKANPzzK2CJlYc6JIkj1wYsfHdavHBNB_w15ug

### Handler refresh token
POST {{url_dev}}user/handlerRefreshToken
Content-Type: application/json
x-client-id: 66cd5835679db0d2bbe6ec47
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmQ1Y2JlYzlkM2QxZjQzNDU5NzU4ODgiLCJlbWFpbCI6IlR1YW5EYXRhM0BnbWFpbC5jb20iLCJpYXQiOjE3MjY1NjY4MzIsImV4cCI6MTcyNjczOTYzMn0.bWJxetiOEEmIrMvBP5VqckbWbGyftz5ucDL3TaAWAGUMea5DDBUD0_0gPLKmKJVlFKuKX05iWQi7eKXQdNMMIYC6eMmH31OOEVfn4EQwj670YvnScnNrRSkBffjCyz8HCTdth8jPIL8j7q5LYMGOM9UVUCOhUA4cbzajwVoxC7sWieEyZF9im6wECjgCUF5206eopqpt2s92TuOOYQ1na-K1WJCN2z8m9osdW4sbJBLwaMwOyOt6Fnl4yOn_IGfkRIT1ZCWaNjisfwiSp3_0OQ73yLFo2xNt3BT8GeeGpGIC6-X-a6Byva1Yhcwxp7Xlp1Pd-JtZR_aAC764lzhbyE01WRlcuyIc4HUpFnVIf1ZpUg_695odYAdrxFvetX5P__xjduTpO2nggQa_Mg2QlZ_f3dOWt0CjnLtHTXpjkVBVoxewgPEqeFyIc3-lTyCjSxnFFRjr1y295Wr2PqHks92vjDNN8dui9FfSjZm2x95uqhESoWXvFijnPkBlXa2vzj0PiofB5bZVOGdlmAjqx-mrp-dkTqlhottZV1MAqJWTM_hInCqqtUJ4ebMKTyF4w4hCX2pGmdG21K18Vpmii-lxl2uKZalMo8UnvXNuuRVMqWOwvaEWs_ebLlQE_L6eLJge53rPmWEdWTTdiKHKV8Zgh1az6O1vetXAQdQ5sFU
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmQ1Y2JlYzlkM2QxZjQzNDU5NzU4ODgiLCJlbWFpbCI6IlR1YW5EYXRhM0BnbWFpbC5jb20iLCJpYXQiOjE3MjY1NjY4MzIsImV4cCI6MTcyNzE3MTYzMn0.PW-Wk8MKsVx0XgnIfG8YYOfCfKeX9Q4ODWu7hcPCrUn8KD8aclqc6L8lpYUMFY6__Cp_xJyNIVw3I9vP-i381wSCxUWJ5Dt7wXglspWCcKg7N92K1XqY1c8XvIXk3qmSLut30LiLgN5xvJF44-bPqNeQU6pHaZ_1h7UQTIVFzN4t2N7rhrjCDT8SUvOneIvO89FUL-kBLRCOE4xKq9NCPHNtEeoS4BnunlIH_xIgfKr7B4oUCO4qC99HUi6QsP5lYwyu8oN82ET1GLyAqQti0ghkTH5-0VwVd_xp4AIULPORuHBZZ8urUvfr7iQlm7ieK923I9mWdYBqK_qGtMuk1kvBjz5hsFTqNqvp099mPwxdFG0gQAK3ewdSDqER6rFlIrc-VctEBcUHEOuYIYP176bRqpD5jEMnlXyXLSAQH9q9Gn6FDgTBNSaHoR00ez_EhhHhsIrI5iX9bq1cmzTxzSF8h339tXqL-4yyuMbILbUTHTx2ierzflGD79YRg_8_vDdAcshuC3tvAuuEJ7kpomQnfoDZzD_doVl6_gxrGZ3tzTfnyUeiuwTIsZ-yPc_VVoOiK4ZYCdbFbIh6DKD04yKQ5YvujtqgprjYNXMoJhZNqLfMtUzOGZQJEVpqMZlFlZmSH0lU4JE8rLaiONmJnKfizVBACa6W3_tB1MXMzO8
